# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisFIRE
                                 A QGIS plugin
 Wildfire simulation & other tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-12
        copyright            : (C) 2020 by Jaume Figueras i Jové
        email                : jaume.figueras@upc.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GisFIRE class from file GisFIRE.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GisFire import GisFIRE
    return GisFIRE(iface)
