# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisFIRE
                                 A QGIS plugin
 Wildfire simulation & other tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-02-12
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Jaume Figueras i Jové
        email                : jaume.figueras@upc.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction
from PyQt5.QtWidgets import QActionGroup
from PyQt5.QtWidgets import QMenu
from PyQt5.QtWidgets import QWidgetAction
from PyQt5.QtWidgets import QDialog
# Initialize Qt resources from file resources.py
from .resources import *
from qgis.gui import QgsMapToolEmitPoint
from qgis.core import QgsProject
from qgis.core import QgsExpressionContextUtils
from qgis.core import QgsExpressionContextScope
from qgis.core import QgsGeometry
from qgis.core import QgsFeature
from qgis.core import QgsPointXY
# Import the code for the DockWidget
from .GisFireSettings import GisFIRESettings
from .GisFireUi import DlgIgnitionPoint
from .GisFireUi import DockControl
from .Helper.Layers import CreateIgnitionPointLayer
from .Helper.Layers import CreatePerimeterLayer
from .Helper.Layers import SaveLayerToGeoPackage

import os.path

class GisFIRE:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GisFIRE_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.toolbarActions = {}
        self.menuActions = {}
        self.layers = {}

        # Load Project
        self.iface.newProjectCreated.connect(self.onNewProject)
        project = QgsProject.instance()
        if (project is not None):
            project.readProject.connect(self.onReadProject)
            project.projectSaved.connect(self.onSavedProject)


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GisFIRE', message)

    def addToolbarActions(self):
        """Create the toolbar buttons that GisFIRE uses as shortcuts."""
        # Toggle GisFIRE Pane
        action = QAction(QIcon(':/plugins/GisFire/gisfire.png'), self.tr('GisFIRE'), None)
        action.triggered.connect(self.onTogglePane)
        action.setEnabled(True)
        action.setCheckable(True)
        action.setStatusTip(self.tr('Toggle GisFIRE Pane'))
        action.setWhatsThis(self.tr('Toggle GisFIRE Pane'))
        self.toolbar.addAction(action)
        self.toolbarActions['gisfire'] = action
        # Convert Project to GisFIRE or back to QGIS
        action = QAction(QIcon(':/plugins/GisFire/convert_project.png'), self.tr('Convert Project'), None)
        action.triggered.connect(self.onConvertProject)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Convert Project to GisFIRE or to Standard QGIS'))
        action.setWhatsThis(self.tr('Convert Project to GisFIRE or to Standard QGIS'))
        self.toolbar.addAction(action)
        self.toolbarActions['convert_project'] = action
        # Set ignition point
        action = QAction(QIcon(':/plugins/GisFire/ignition_point.png'), self.tr('Set Ignition Point'), None)
        action.triggered.connect(self.onSetIgnitionPoint)
        action.setEnabled(True)
        action.setCheckable(True)
        action.setStatusTip(self.tr('Set Ignition Point'))
        action.setWhatsThis(self.tr('Set Ignition Point'))
        self.toolbar.addAction(action)
        self.toolbarActions['ignition_point'] = action
        # Separator
        self.toolbar.addSeparator()
        # Simulation Play
        action = QAction(QIcon(':/plugins/GisFire/play.png'), self.tr('Run Simulation'), None)
        action.triggered.connect(self.onRunSimulation)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Full run of the Fire Spread simulation'))
        action.setWhatsThis(self.tr('Full run of the Fire Spread simulation'))
        self.toolbar.addAction(action)
        self.toolbarActions['run_simulation'] = action
        # Simulation Step
        action = QAction(QIcon(':/plugins/GisFire/next.png'), self.tr('Step Simulation'), None)
        action.triggered.connect(self.onStepSimulation)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Run one step of the Fire Spread simulation'))
        action.setWhatsThis(self.tr('Run one step of the Fire Spread simulation'))
        self.toolbar.addAction(action)
        self.toolbarActions['step_simulation'] = action
        # Simulation Pause
        action = QAction(QIcon(':/plugins/GisFire/pause.png'), self.tr('Pause Simulation'), None)
        action.triggered.connect(self.onPauseSimulation)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Pause the Fire Spread simulation'))
        action.setWhatsThis(self.tr('Pause the Fire Spread simulation'))
        self.toolbar.addAction(action)
        self.toolbarActions['pause_simulation'] = action
        # Simulation Stop
        action = QAction(QIcon(':/plugins/GisFire/stop.png'), self.tr('Stop Simulation'), None)
        action.triggered.connect(self.onStopSimulation)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Stop the Fire Spread simulation'))
        action.setWhatsThis(self.tr('Stop the Fire Spread simulation'))
        self.toolbar.addAction(action)
        self.toolbarActions['stop_simulation'] = action

    def addMenuActions(self):
        """Create the menu entries that allow GisFIRE procedures."""
        # Toggle GisFIRE Pane
        action = self.menu.addAction(self.tr('Toggle GisFIRE Pane'))
        action.setIcon(QIcon(':/plugins/GisFire/gisfire.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onTogglePane)
        self.menuActions['gisfire'] = action
        # Convert Project to GisFIRE or back to QGIS
        action = self.menu.addAction(self.tr('Convert Project'))
        action.setIcon(QIcon(':/plugins/GisFire/convert_project.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onConvertProject)
        self.menuActions['convert_project'] = action
        # Set ignition point
        action = self.menu.addAction(self.tr('Set Ignition Point'))
        action.setIcon(QIcon(':/plugins/GisFire/ignition_point.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onSetIgnitionPoint)
        self.menuActions['ignition_point'] = action
        # Separator
        self.menu.addSeparator()
        # Simulation Play
        action = self.menu.addAction(self.tr('Run Simulation'))
        action.setIcon(QIcon(':/plugins/GisFire/play.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onRunSimulation)
        self.menuActions['run_simulation'] = action
        # Simulation Step
        action = self.menu.addAction(self.tr('Step Simulation'))
        action.setIcon(QIcon(':/plugins/GisFire/next.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onStepSimulation)
        self.menuActions['step_simulation'] = action
        # Simulation Pause
        action = self.menu.addAction(self.tr('Pause Simulation'))
        action.setIcon(QIcon(':/plugins/GisFire/pause.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onPauseSimulation)
        self.menuActions['pause_simulation'] = action
        # Simulation Stop
        action = self.menu.addAction(self.tr('Stop Simulation'))
        action.setIcon(QIcon(':/plugins/GisFire/stop.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onStopSimulation)
        self.menuActions['stop_simulation'] = action

    def addRelations(self):
        """Create mutually exclusive relations between toolbar buttons."""
        # Get the nav toolbar actions
        actions = self.iface.mapNavToolToolBar().actions()
        # Build a group with actions and add GisFIRE actions
        group = QActionGroup(self.iface.mainWindow())
        group.setExclusive(True)
        for action in actions:
            group.addAction(action)
        group.addAction(self.toolbarActions['ignition_point'])

    def initGui(self):
        """Initializes the QGIS GUI for the GisFIRE plugin."""
        # setup the menu
        self.menu = QMenu(self.tr(u'Gis&FIRE'), self.iface.mainWindow().menuBar())
        actions = self.iface.mainWindow().menuBar().actions()
        lastAction = actions[-1]
        self.iface.mainWindow().menuBar().insertMenu(lastAction, self.menu)
        #setup the toolbar
        self.toolbar = self.iface.addToolBar(u'GisFIRE')
        self.toolbar.setObjectName(u'GisFIRE')
        #setup the GisFire pane
        self.dockwidget = None

        # Add toolbar buttons
        self.addToolbarActions()
        # Add menu entries
        self.addMenuActions()
        # Create relations with existing menus and buttons
        self.addRelations()

    def disableMenusAndToolbars(self):
        self.toolbarActions['gisfire'].setEnabled(False)
        self.toolbarActions['convert_project'].setEnabled(False)
        self.toolbarActions['ignition_point'].setEnabled(False)
        self.toolbarActions['run_simulation'].setEnabled(False)
        self.toolbarActions['step_simulation'].setEnabled(False)
        self.toolbarActions['pause_simulation'].setEnabled(False)
        self.toolbarActions['stop_simulation'].setEnabled(False)
        self.menuActions['gisfire'].setEnabled(False)
        self.menuActions['convert_project'].setEnabled(False)
        self.menuActions['ignition_point'].setEnabled(False)
        self.menuActions['run_simulation'].setEnabled(False)
        self.menuActions['step_simulation'].setEnabled(False)
        self.menuActions['pause_simulation'].setEnabled(False)
        self.menuActions['stop_simulation'].setEnabled(False)

    def disableConvertProject(self):
        self.toolbarActions['convert_project'].setEnabled(False)
        self.menuActions['convert_project'].setEnabled(False)

    def enableMenusAndToolbars(self):
        self.toolbarActions['gisfire'].setEnabled(True)
        self.toolbarActions['convert_project'].setEnabled(True)
        self.toolbarActions['ignition_point'].setEnabled(True)
        self.toolbarActions['run_simulation'].setEnabled(True)
        self.toolbarActions['step_simulation'].setEnabled(True)
        self.toolbarActions['pause_simulation'].setEnabled(True)
        self.toolbarActions['stop_simulation'].setEnabled(True)
        self.menuActions['gisfire'].setEnabled(True)
        self.menuActions['convert_project'].setEnabled(True)
        self.menuActions['ignition_point'].setEnabled(True)
        self.menuActions['run_simulation'].setEnabled(True)
        self.menuActions['step_simulation'].setEnabled(True)
        self.menuActions['pause_simulation'].setEnabled(True)
        self.menuActions['stop_simulation'].setEnabled(True)

    def enableConvertProject(self):
        self.toolbarActions['convert_project'].setEnabled(True)
        self.menuActions['convert_project'].setEnabled(True)

    #--------------------------------------------------------------------------

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # Remove toolbar items
        for action in self.toolbarActions.values():
            action.triggered.disconnect()
            self.iface.removeToolBarIcon(action)
            action.deleteLater()
        # Remove toolbar
        self.toolbar.deleteLater()
        # Remove menu items
        for action in self.menuActions.values():
            action.triggered.disconnect()
            self.menu.removeAction(action)
            action.deleteLater()
        # Remove menu
        self.menu.deleteLater()
        # Remove dockwidget
        if self.dockwidget != None:
            self.dockwidget.hide()
            self.dockwidget.deleteLater()
        # Remove
        self.iface.newProjectCreated.disconnect(self.onNewProject)
        project = QgsProject.instance()
        if (project is not None):
            project.readProject.disconnect(self.onReadProject)
            project.projectSaved.disconnect(self.onSavedProject)

    #--------------------------------------------------------------------------

    def onReadProject(self):
        if self.isAGisFireProject():
            project = QgsProject.instance()
            if (project is not None):
                scope = QgsExpressionContextUtils.projectScope(project)
                self.prepareProject(project, scope)
        else:
            self.enableConvertProject()

    def onNewProject(self):
        self.disableMenusAndToolbars()

    def onSavedProject(self):
        self.enableConvertProject()

    #--------------------------------------------------------------------------

    def onTogglePane(self):
        """Event listener to show/hide the dock pane"""
        if self.dockwidget == None:
            # Create the dockwidget if it is not et created
            self.dockwidget = DockControl()
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
            self.toolbarActions['gisfire'].setChecked(True)
        else:
            # Switch visibilityy and mantain consistency with toolbar button
            if self.dockwidget.isVisible():
                self.dockwidget.hide()
                self.toolbarActions['gisfire'].setChecked(False)
            else:
                self.dockwidget.show()
                self.toolbarActions['gisfire'].setChecked(True)

    #--------------------------------------------------------------------------

    def isAGisFireProject(self):
        project = QgsProject.instance()
        if (project is not None):
            scope = QgsExpressionContextUtils.projectScope(project)
            if (scope.hasVariable('gis_fire_version')):
                return True
            else:
                return False

    def prepareProject(self, project, scope):
        project_name = scope.variable('project_basename')
        project_location = scope.variable('project_home')
        self.geo_package = project_location + '/' + project_name + '.gpkg'
        ignition_layer = CreateIgnitionPointLayer(self.iface, project, self.geo_package)
        self.layers['ignition_layer'] = ignition_layer
        perimeter_layer = CreatePerimeterLayer(self.iface, project, self.geo_package)
        self.layers['perimeter_layer'] = perimeter_layer
        self.enableMenusAndToolbars()
        #scope.addVariable(QgsExpressionContextScope.StaticVariable("gis_fire_version", "0.11", True, True, "GisFIRE version"))
        #scope.setVariable("gis_fire_version", "0.11")

    def onConvertProject(self):
        """Event listener to convert a project to a GisFire Compliant project or
        back to a standard QGIS project"""
        if self.isAGisFireProject():
            project = QgsProject.instance()
            QgsExpressionContextUtils.removeProjectVariable(project, GisFIRESettings.VERSION_VARIABLE_NAME)
            self.disableMenusAndToolbars()
        else:
            project = QgsProject.instance()
            scope = QgsExpressionContextUtils.projectScope(project)
            QgsExpressionContextUtils.setProjectVariable(project, GisFIRESettings.VERSION_VARIABLE_NAME, GisFIRESettings.VERSION)
            self.prepareProject(project, scope)

    #--------------------------------------------------------------------------

    def onSetIgnitionPoint(self):
        project = QgsProject.instance()
        canvas = self.iface.mapCanvas()
        self.previousTool = canvas.mapTool()
        self.pointTool = QgsMapToolEmitPoint(canvas)
        self.pointTool.canvasClicked.connect(self.setIgnitionPointCallback)
        canvas.setMapTool(self.pointTool)
        print("onSetIgnitionPoint")

    def setIgnitionPointCallback(self, point, mouse_button):
        self.pointTool.canvasClicked.disconnect()
        canvas = self.iface.mapCanvas()
        canvas.setMapTool(self.previousTool)
        if mouse_button == Qt.LeftButton:
            dlg = DlgIgnitionPoint(self.iface.mainWindow())
            result = dlg.exec_()
            if result == QDialog.Accepted:
                feat = QgsFeature(self.layers['ignition_layer'].fields())
                feat.setAttribute('date', dlg.getDateTime())
                feat.setGeometry(QgsGeometry.fromPointXY(point))
                (res, outFeats) = self.layers['ignition_layer'].dataProvider().addFeatures([feat])
                self.layers['ignition_layer'].updateExtents()
                self.layers['ignition_layer'].triggerRepaint()
                SaveLayerToGeoPackage(self.layers['ignition_layer'], self.geo_package)

    #--------------------------------------------------------------------------

    def onRunSimulation(self):
        pass

    def onStepSimulation(self):
        pass

    def onPauseSimulation(self):
        pass

    def onStopSimulation(self):
        pass
