# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisFIRE
                                 A QGIS plugin
 Wildfire simulation & other tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-02-12
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Jaume Figueras i Jové
        email                : jaume.figueras@upc.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtCore import Qt
from PyQt5.QtCore import QVariant
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction
from PyQt5.QtWidgets import QActionGroup
from PyQt5.QtWidgets import QMenu
from PyQt5.QtWidgets import QWidgetAction
from PyQt5.QtWidgets import QDialog
# Initialize Qt resources from file resources.py
from qgis.gui import QgsMapToolEmitPoint
from qgis.core import QgsProject
from qgis.core import QgsExpressionContextUtils
from qgis.core import QgsExpressionContextScope
from qgis.core import QgsGeometry
from qgis.core import QgsFeature
from qgis.core import QgsPointXY
from qgis.core import QgsApplication
# Import the code for the DockWidget
from .resources import *
from .GisFireSettings import GisFIRESettings
from .GisFireUi import DlgIgnitionPoint
from .GisFireUi import DockControl
from .Helper import Layers
from .Helper import Utils
# Import simulation
from .SpreadSimulation import Simulator


import os.path

class GisFIRE:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # Save location where the plugin directory is located
        self.plugin_dir = os.path.dirname(__file__)

        # Initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GisFIRE_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Initialization of UI references
        self.toolbarActions = {}
        self.menuActions = {}
        # Initialization of GisFIRE data layers
        self.layers = {}
        # Initialization of simulator structure
        self._simulator = {}
        self._simulator["init"] = False
        self._simulator["simulator"] = None
        # UI elements
        self._pointTool = None
        self._previousTool = None

        # Connect to project signals to allow plugin interacton when a new
        # project is created or loaded
        self.iface.newProjectCreated.connect(self.onNewProject)
        project = QgsProject.instance()
        if (project is not None):
            project.readProject.connect(self.onReadProject)
            project.projectSaved.connect(self.onSavedProject)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GisFIRE', message)

    def _addToolbarActions(self):
        """Create the toolbar buttons that GisFIRE uses as shortcuts."""
        # Toggle GisFIRE Pane
        action = QAction(QIcon(':/plugins/GisFire/gisfire.png'), self.tr('GisFIRE'), None)
        action.triggered.connect(self.onTogglePane)
        action.setEnabled(True)
        action.setCheckable(True)
        action.setStatusTip(self.tr('Toggle GisFIRE Pane'))
        action.setWhatsThis(self.tr('Toggle GisFIRE Pane'))
        self.toolbar.addAction(action)
        self.toolbarActions['gisfire'] = action
        # Convert Project to GisFIRE or back to QGIS
        action = QAction(QIcon(':/plugins/GisFire/convert_project.png'), self.tr('Convert Project'), None)
        action.triggered.connect(self.onConvertProject)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Convert Project to GisFIRE or to Standard QGIS'))
        action.setWhatsThis(self.tr('Convert Project to GisFIRE or to Standard QGIS'))
        self.toolbar.addAction(action)
        self.toolbarActions['convert_project'] = action
        # Set ignition point
        action = QAction(QIcon(':/plugins/GisFire/ignition_point.png'), self.tr('Set Ignition Point'), None)
        action.triggered.connect(self.onSetIgnitionPoint)
        action.setEnabled(True)
        action.setCheckable(True)
        action.setStatusTip(self.tr('Set Ignition Point'))
        action.setWhatsThis(self.tr('Set Ignition Point'))
        self.toolbar.addAction(action)
        self.toolbarActions['ignition_point'] = action
        # Separator
        self.toolbar.addSeparator()
        # Simulation Play
        action = QAction(QIcon(':/plugins/GisFire/play.png'), self.tr('Run Simulation'), None)
        action.triggered.connect(self.onRunSimulation)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Full run of the Fire Spread simulation'))
        action.setWhatsThis(self.tr('Full run of the Fire Spread simulation'))
        self.toolbar.addAction(action)
        self.toolbarActions['run_simulation'] = action
        # Simulation Step
        action = QAction(QIcon(':/plugins/GisFire/next.png'), self.tr('Step Simulation'), None)
        action.triggered.connect(self.onStepSimulation)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Run one step of the Fire Spread simulation'))
        action.setWhatsThis(self.tr('Run one step of the Fire Spread simulation'))
        self.toolbar.addAction(action)
        self.toolbarActions['step_simulation'] = action
        # Simulation Pause
        action = QAction(QIcon(':/plugins/GisFire/pause.png'), self.tr('Pause Simulation'), None)
        action.triggered.connect(self.onPauseSimulation)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Pause the Fire Spread simulation'))
        action.setWhatsThis(self.tr('Pause the Fire Spread simulation'))
        self.toolbar.addAction(action)
        self.toolbarActions['pause_simulation'] = action
        # Simulation Stop
        action = QAction(QIcon(':/plugins/GisFire/stop.png'), self.tr('Stop Simulation'), None)
        action.triggered.connect(self.onStopSimulation)
        action.setEnabled(True)
        action.setCheckable(False)
        action.setStatusTip(self.tr('Stop the Fire Spread simulation'))
        action.setWhatsThis(self.tr('Stop the Fire Spread simulation'))
        self.toolbar.addAction(action)
        self.toolbarActions['stop_simulation'] = action

    def _addMenuActions(self):
        """Create the menu entries that allow GisFIRE procedures."""
        # Toggle GisFIRE Pane
        action = self.menu.addAction(self.tr('Toggle GisFIRE Pane'))
        action.setIcon(QIcon(':/plugins/GisFire/gisfire.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onTogglePane)
        self.menuActions['gisfire'] = action
        # Convert Project to GisFIRE or back to QGIS
        action = self.menu.addAction(self.tr('Convert Project'))
        action.setIcon(QIcon(':/plugins/GisFire/convert_project.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onConvertProject)
        self.menuActions['convert_project'] = action
        # Set ignition point
        action = self.menu.addAction(self.tr('Set Ignition Point'))
        action.setIcon(QIcon(':/plugins/GisFire/ignition_point.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onSetIgnitionPoint)
        self.menuActions['ignition_point'] = action
        # Separator
        self.menu.addSeparator()
        # Simulation Play
        action = self.menu.addAction(self.tr('Run Simulation'))
        action.setIcon(QIcon(':/plugins/GisFire/play.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onRunSimulation)
        self.menuActions['run_simulation'] = action
        # Simulation Step
        action = self.menu.addAction(self.tr('Step Simulation'))
        action.setIcon(QIcon(':/plugins/GisFire/next.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onStepSimulation)
        self.menuActions['step_simulation'] = action
        # Simulation Pause
        action = self.menu.addAction(self.tr('Pause Simulation'))
        action.setIcon(QIcon(':/plugins/GisFire/pause.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onPauseSimulation)
        self.menuActions['pause_simulation'] = action
        # Simulation Stop
        action = self.menu.addAction(self.tr('Stop Simulation'))
        action.setIcon(QIcon(':/plugins/GisFire/stop.png'))
        action.setIconVisibleInMenu(True)
        action.triggered.connect(self.onStopSimulation)
        self.menuActions['stop_simulation'] = action

    def _addRelations(self):
        """Create mutually exclusive relations between toolbar buttons."""
        # Get the nav toolbar actions
        actions = self.iface.mapNavToolToolBar().actions()
        # Build a group with actions and add GisFIRE actions
        group = QActionGroup(self.iface.mainWindow())
        group.setExclusive(True)
        for action in actions:
            group.addAction(action)
        group.addAction(self.toolbarActions['ignition_point'])

    def _disableMenusAndToolbars(self):
        """Disables all menu items and toolbar buttons of the GisFIRE UI"""
        self.toolbarActions['gisfire'].setEnabled(False)
        self.toolbarActions['convert_project'].setEnabled(False)
        self.toolbarActions['ignition_point'].setEnabled(False)
        self.toolbarActions['run_simulation'].setEnabled(False)
        self.toolbarActions['step_simulation'].setEnabled(False)
        self.toolbarActions['pause_simulation'].setEnabled(False)
        self.toolbarActions['stop_simulation'].setEnabled(False)
        self.menuActions['gisfire'].setEnabled(False)
        self.menuActions['convert_project'].setEnabled(False)
        self.menuActions['ignition_point'].setEnabled(False)
        self.menuActions['run_simulation'].setEnabled(False)
        self.menuActions['step_simulation'].setEnabled(False)
        self.menuActions['pause_simulation'].setEnabled(False)
        self.menuActions['stop_simulation'].setEnabled(False)

    def disableConvertProject(self):
        """Disables the convert project (from and to GisFIRE) menu items and
        toolbar buttons of the GisFIRE UI
        """
        self.toolbarActions['convert_project'].setEnabled(False)
        self.menuActions['convert_project'].setEnabled(False)

    def _enableMenusAndToolbars(self):
        """Enables all menu items and toolbar buttons of the GisFIRE UI"""
        self.toolbarActions['gisfire'].setEnabled(True)
        self.toolbarActions['convert_project'].setEnabled(True)
        self.toolbarActions['ignition_point'].setEnabled(True)
        self.toolbarActions['run_simulation'].setEnabled(True)
        self.toolbarActions['step_simulation'].setEnabled(True)
        self.toolbarActions['pause_simulation'].setEnabled(True)
        self.toolbarActions['stop_simulation'].setEnabled(True)
        self.menuActions['gisfire'].setEnabled(True)
        self.menuActions['convert_project'].setEnabled(True)
        self.menuActions['ignition_point'].setEnabled(True)
        self.menuActions['run_simulation'].setEnabled(True)
        self.menuActions['step_simulation'].setEnabled(True)
        self.menuActions['pause_simulation'].setEnabled(True)
        self.menuActions['stop_simulation'].setEnabled(True)

    def _enableConvertProject(self):
        """Disables the convert project (from and to GisFIRE) menu items and
        toolbar buttons of the GisFIRE UI
        """
        self.toolbarActions['convert_project'].setEnabled(True)
        self.menuActions['convert_project'].setEnabled(True)

    def initGui(self):
        """Initializes the QGIS GUI for the GisFIRE plugin."""
        # setup the menu
        self.menu = QMenu(self.tr(u'Gis&FIRE'), self.iface.mainWindow().menuBar())
        actions = self.iface.mainWindow().menuBar().actions()
        lastAction = actions[-1]
        self.iface.mainWindow().menuBar().insertMenu(lastAction, self.menu)
        #setup the toolbar
        self.toolbar = self.iface.addToolBar(u'GisFIRE')
        self.toolbar.setObjectName(u'GisFIRE')
        #setup the GisFire pane
        self.dockwidget = None

        # Add toolbar buttons
        self._addToolbarActions()
        # Add menu entries
        self._addMenuActions()
        # Create relations with existing menus and buttons
        self._addRelations()
        # If there is an open project (that has been already saved) check if it
        # is a GisFIRE project and enable toolbar buttons and menus
        project_name = Utils.getProjectVariable(QgsProject.instance(), 'project_basename')
        if not type(project_name) is str:
            self._disableMenusAndToolbars()
        else:
            if Utils.isAGisFireProject(QgsProject.instance()):
                self._enableMenusAndToolbars()
                self._prepareProject()
            else:
                self._disableMenusAndToolbars()
                self._enableConvertProject()

    #--------------------------------------------------------------------------

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # Remove toolbar items
        for action in self.toolbarActions.values():
            action.triggered.disconnect()
            self.iface.removeToolBarIcon(action)
            action.deleteLater()
        # Remove toolbar
        self.toolbar.deleteLater()
        # Remove menu items
        for action in self.menuActions.values():
            action.triggered.disconnect()
            self.menu.removeAction(action)
            action.deleteLater()
        # Remove menu
        self.menu.deleteLater()
        # Remove dockwidget
        if self.dockwidget != None:
            self.dockwidget.hide()
            self.dockwidget.deleteLater()
        # Remove
        self.iface.newProjectCreated.disconnect(self.onNewProject)
        project = QgsProject.instance()
        if (project is not None):
            project.readProject.disconnect(self.onReadProject)
            project.projectSaved.disconnect(self.onSavedProject)

    #--------------------------------------------------------------------------

    def onReadProject(self):
        """Slot connection for the Read Project signal. It checks if the loadaed
        project is a GisFIRE project and updates the GisFIRE UI agordingly"""
        if Utils.isAGisFireProject(QgsProject.instance()):
            self._prepareProject()
            self._enableMenusAndToolbars()
        else:
            self._enableConvertProject()

    def onNewProject(self):
        """Slot connection for the New Project signal. It disables all the
        GisFIRE UI because the project has to be saved to be converted to a
        GisFIRE project"""
        self._disableMenusAndToolbars()

    def onSavedProject(self):
        """Slot connection for the Save Project signal. It enables convert
        project UI because once the project is saved it can be converted to a
        GisFIRE project"""
        if not Utils.isAGisFireProject(QgsProject.instance()):
            self._enableConvertProject()

    #--------------------------------------------------------------------------

    def onTogglePane(self):
        """Event listener to show/hide the dock pane"""
        if self.dockwidget == None:
            # Create the dockwidget if it is not et created
            self.dockwidget = DockControl()
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
            self.toolbarActions['gisfire'].setChecked(True)
        else:
            # Switch visibilityy and mantain consistency with toolbar button
            if self.dockwidget.isVisible():
                self.dockwidget.hide()
                self.toolbarActions['gisfire'].setChecked(False)
            else:
                self.dockwidget.show()
                self.toolbarActions['gisfire'].setChecked(True)

    #--------------------------------------------------------------------------

    def _prepareProject(self):
        """Set up of the different layers and storage (in a geopackage file) to
        manage all the information needed by the project"""
        # Set up the geopackage
        project_name = Utils.getProjectVariable(QgsProject.instance(), 'project_basename')
        project_location = Utils.getProjectVariable(QgsProject.instance(), 'project_home')
        self.geo_package = project_location + '/' + project_name + '.gpkg'
        # Set up the layers
        ignition_layer = Layers.CreateIgnitionPointLayer(self.iface, QgsProject.instance(), self.geo_package)
        self.layers[GisFIRESettings.IGNITION_LAYER_ID] = ignition_layer
        perimeter_layer = Layers.CreatePerimeterLayer(self.iface, QgsProject.instance(), self.geo_package)
        self.layers[GisFIRESettings.PERIMETER_LAYER_ID] = perimeter_layer
        models_layer = Layers.CreateModelsLayer(self.iface, QgsProject.instance(), self.geo_package)
        self.layers[GisFIRESettings.FIREMODELS_LAYER_ID] = models_layer

    def onConvertProject(self):
        """Slot of the convert button signal to convert a project to a GisFire
        Compliant project or back to a standard QGIS project"""
        if Utils.isAGisFireProject(QgsProject.instance()):
            # Remove the information of the GisFIRE project
            Utils.removeProjectVariable(QgsProject.instance(), GisFIRESettings.VERSION_VARIABLE_NAME)
            self._disableMenusAndToolbars()
            self._enableConvertProject()
        else:
            # Add the project variables and layers of a valid GisFIRE project
            Utils.setProjectVariable(QgsProject.instance(), GisFIRESettings.VERSION_VARIABLE_NAME, GisFIRESettings.VERSION)
            self._prepareProject()
            self._enableMenusAndToolbars()

    #--------------------------------------------------------------------------

    def onSetIgnitionPoint(self):
        """Slot of the ignition point button signal to set an ignition point for
        a wildfire. This procedure sets a new slot to the onClick signal when
        the user clicks on the map canvas"""
        # Clean in case other point creation was aborted
        if not (self._pointTool is None):
            self._pointTool.canvasClicked.disconnect()
            del(self._pointTool)
            self._previousTool = None
            self._pointTool = None
        # Store the previous tool in use b the user
        canvas = self.iface.mapCanvas()
        self._previousTool = canvas.mapTool()
        # Set the tool and onClick callback
        self._pointTool = QgsMapToolEmitPoint(canvas)
        self._pointTool.canvasClicked.connect(self._setIgnitionPointCallback)
        canvas.setMapTool(self._pointTool)
        print("Click: set point")

    def _setIgnitionPointCallback(self, point, mouse_button):
        """Slot callback for the onClick signal on the map canvas when a new
        ignition point is assigned

        :param point: Point in map units where the mouse has been clicked
        :type point: QgsPointXY

        :param mouse_button: Characteristics of the clicked mouse button
        :type mouse_button: Qt.MouseButton
        """
        # Clean the signal, slot and mouse icon created before
        self._pointTool.canvasClicked.disconnect()
        print("Click: set point CALLBACK")
        if mouse_button == Qt.LeftButton:
            # Create the dialog in charge of collecting needed data
            dlg = DlgIgnitionPoint(self.iface.mainWindow())
            result = dlg.exec_()
            if result == QDialog.Accepted:
                Layers.AddIgnitionPoint(self.layers[GisFIRESettings.IGNITION_LAYER_ID], QgsGeometry.fromPointXY(point), dlg.getDateTime(), 0, 0)
                Layers.LayerToGeoPackage(self.layers[GisFIRESettings.IGNITION_LAYER_ID], self.geo_package)
        canvas = self.iface.mapCanvas()
        canvas.setMapTool(self._previousTool)
        del(self._pointTool)
        self._previousTool = None
        self._pointTool = None

    #--------------------------------------------------------------------------

    def onRunSimulation(self):
        pass

    def onStepSimulation(self):
        for i in range(0, 1):#24*60*2):
            if self._simulator['simulator'] is None:
                simulator = Simulator.SpreadSimulator()
                simulator.ignitionLayer = self.layers[GisFIRESettings.IGNITION_LAYER_ID]
                simulator.perimeterLayer = self.layers[GisFIRESettings.PERIMETER_LAYER_ID]
                simulator.fuelLayer = self.layers[GisFIRESettings.FIREMODELS_LAYER_ID]
                self._simulator['simulator'] = simulator
                self._simulator['init'] = False
            if not self._simulator['init']:
                self._simulator['init'] = True
                self._simulator['simulator'].initilizeSimulation()
            self._simulator['simulator'].step()
            if self.iface.mapCanvas().isCachingEnabled():
                self.layers[GisFIRESettings.IGNITION_LAYER_ID].triggerRepaint()
                self.layers[GisFIRESettings.PERIMETER_LAYER_ID].triggerRepaint()
            else:
                self.iface.mapCanvas().refresh()
            QCoreApplication.processEvents()
            QgsApplication.processEvents()

    def onPauseSimulation(self):
        pass

    def onStopSimulation(self):
        pass
