"""add time zone areas, wildfire zone and country

Revision ID: f6f5319de6bf
Revises: 42c012409131
Create Date: 2026-07-21 19:13:05.265195+00:00
"""
from __future__ import annotations

from typing import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'f6f5319de6bf'
down_revision: str | None = '42c012409131'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Name of the wildfire -> admin_boundary foreign key.
#:
#: Spelled out rather than left to Alembic, which generates ``None`` here and a
#: ``drop_constraint(None, ...)`` in the downgrade that cannot run. The value is
#: exactly what PostgreSQL would have picked on its own, so a database built by
#: these migrations and one built by ``Base.metadata.create_all()`` still match.
ADMIN_BOUNDARY_FK = "wildfire_admin_boundary_id_fkey"


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('time_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_geospatial_index('idx_time_zone_geometry', 'time_zone', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_column('wildfire', sa.Column('time_zone', sa.String(), nullable=True))
    op.add_column('wildfire', sa.Column('admin_boundary_id', sa.Integer(), nullable=True))
    op.create_index('ix_wildfire_admin_boundary_id', 'wildfire', ['admin_boundary_id'], unique=False)
    op.create_index('ix_wildfire_start_date_time', 'wildfire', ['start_date_time'], unique=False)
    op.create_foreign_key(ADMIN_BOUNDARY_FK, 'wildfire', 'admin_boundary', ['admin_boundary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(ADMIN_BOUNDARY_FK, 'wildfire', type_='foreignkey')
    op.drop_index('ix_wildfire_start_date_time', table_name='wildfire')
    op.drop_index('ix_wildfire_admin_boundary_id', table_name='wildfire')
    op.drop_column('wildfire', 'admin_boundary_id')
    op.drop_column('wildfire', 'time_zone')
    op.drop_geospatial_index('idx_time_zone_geometry', table_name='time_zone', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('time_zone')
    # ### end Alembic commands ###
