"""gwis id is not unique

The published GlobFire v3 files repeat ``Id`` across genuinely different fires —
359 times over the 23,299,416 fires of the 2000-2021 files — so the unique
constraint the table was created with is not satisfiable by the real data and
aborted the import. Replaced with a plain index, which is what the column is
actually used for. See :class:`~src.providers.gwis.wildfire.GwisWildfire`.

The downgrade puts the constraint back, and will fail if colliding fires have
been imported in the meantime. That is correct: there is no way to restore the
constraint without deciding which of each pair to delete, and this migration must
not make that choice silently.

Revision ID: 065ea7408253
Revises: f6f5319de6bf
Create Date: 2026-07-21 20:03:45.627109+00:00
"""
from __future__ import annotations

from typing import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '065ea7408253'
down_revision: str | None = 'f6f5319de6bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('gwis_wildfire_gwis_id_key'), 'gwis_wildfire', type_='unique')
    op.create_index(op.f('ix_gwis_wildfire_gwis_id'), 'gwis_wildfire', ['gwis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gwis_wildfire_gwis_id'), table_name='gwis_wildfire')
    op.create_unique_constraint(op.f('gwis_wildfire_gwis_id_key'), 'gwis_wildfire', ['gwis_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
