"""add gwis wildfire

Revision ID: 8073d0a07f27
Revises: 563e89574195
Create Date: 2026-07-19 23:07:40.868169+00:00
"""
from __future__ import annotations

from typing import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8073d0a07f27'
down_revision: str | None = '563e89574195'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gwis_wildfire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gwis_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['wildfire.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gwis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gwis_wildfire')
    # ### end Alembic commands ###
