"""add canada nbac and nfdb wildfires

Revision ID: cb6f71e0e868
Revises: 7d2e51b8c39f
Create Date: 2026-08-04 20:02:29.559984+00:00
"""
from __future__ import annotations

from typing import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op
from geoalchemy2 import Geometry
# revision identifiers, used by Alembic.
revision: str = 'cb6f71e0e868'
down_revision: str | None = '7d2e51b8c39f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision.

    Canada arrives as **two providers**, one agency and two products, and three
    tables. ``nfdb_wildfire`` and ``nfdb_ignition`` are the agencies' own fire
    reports — 448,602 points, of which 195,240 are natural-cause, the largest
    lightning-attributable set in GisFIRE. ``nbac_wildfire`` is the National Burned
    Area Composite, 51,818 mapped fire events over 1973-2025.

    Five things about them are worth reading before changing any of the three.

    **The NFDB tables are created first because the NBAC one points at them.**
    ``nbac_wildfire.nfdb_wildfire_id`` is the link from a perimeter to the agency
    report for the same fire, in the direction ``darpa_wildfire.egif_wildfire_id``
    goes: the shape points at the record the fire is filed under. It is created here
    and **filled in by nothing**, so that the application which eventually matches
    the two datasets is an ``UPDATE`` rather than another migration, and
    ``match_method``/``match_confidence``/``matched_at`` come with it because a link
    with no account of how it was made is unusable.

    What this revision deliberately does **not** create is a check constraint on the
    *values* of ``match_method``. Unlike Catalonia and Andalusia, the two Canadian
    datasets share **no published identifier at all** — there is no code here that is
    secretly the other's key — so a binding will rest on date, place and geometry,
    and a vocabulary invented now would be a guess frozen into the schema. Adding the
    constraint later is a one-line revision, exactly as it was for REDIAM.

    **Both geometries are kept in EPSG:3978 as well as EPSG:4326.** NAD83 / Canada
    Atlas Lambert is what both products publish, and both tables get a spatial index
    of their own on it — including ``nfdb_ignition``, which is the first *ignition*
    table in the schema to carry a projected copy. Greece's does not, because Greece
    publishes degrees and the copy would be the same two numbers twice; Canada
    publishes metres, so the EPSG:4326 point is a reprojection and the grid
    coordinates are the originals.

    Note that the NBAC ``.prj`` carries these parameters with **no EPSG identifier**
    and the import asserts 3978 rather than reading it. The NFDB one declares it
    properly.

    **``nbac_wildfire`` is unique twice over and ``nfdb_wildfire`` not at all.** GID
    (the fire year and NFIREID run together) and ``(year, nfireid)`` are both unique
    on the composite, which is the cheapest possible statement that the import's
    dissolve of the boundary-split polygons worked — 52,276 published polygons are
    51,818 fires. NFDB gets no unique constraint anywhere: ``NFDBFIREID`` has 1,684
    duplicates over 448,602 rows and ``FIRE_ID`` only 338,313 distinct values, so a
    ``UNIQUE`` would reject records the service really published, exactly as it would
    for ``gwis_wildfire.gwis_id``.

    **The causes are constrained and the refinement is not.** ``FIRECAUS`` takes
    three values defined in the published metadata (Natural/Human/Undetermined) and
    ``CAUSE`` three single letters (N/H/U); both are stable and both get a ``CHECK``.
    ``CAUSE2`` does not: it adds ``H-PB`` and ``RE`` today and is the column an agency
    would extend first.

    Neither *Natural* nor *N* is a lightning category. Both are the nearest proxy,
    as in ``icnf_wildfire`` and unlike EGIF's named ``Rayo``; see the provider
    modules.

    **Only NBAC has a date precision.** It publishes two independent date pairs —
    satellite hotspot and agency-reported — and for some fires neither, so
    ``date_source`` and ``date_time_precision`` record which was used and how much of
    it is real. NFDB has no second date to fall back on, so a row without a
    ``REP_DATE`` is refused at import rather than dated to 1 January, and every
    stored row therefore has a published day.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('nfdb_ignition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfdb_fire_id', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('src_agency', sa.String(), nullable=True),
    sa.Column('geometry_lambert', Geometry(geometry_type='POINT', srid=3978, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ignition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_nfdb_ignition_geometry_lambert', 'nfdb_ignition', ['geometry_lambert'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_nfdb_ignition_nfdb_fire_id', 'nfdb_ignition', ['nfdb_fire_id'], unique=False)
    op.create_index('ix_nfdb_ignition_year', 'nfdb_ignition', ['year'], unique=False)
    op.create_table('nfdb_wildfire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfdb_fire_id', sa.String(), nullable=True),
    sa.Column('agency_fire_id', sa.String(), nullable=True),
    sa.Column('fire_name', sa.String(), nullable=True),
    sa.Column('src_agency', sa.String(), nullable=False),
    sa.Column('nat_park', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('size_ha', sa.Float(), nullable=True),
    sa.Column('fire_cause', sa.String(), nullable=False),
    sa.Column('fire_cause_detail', sa.String(), nullable=True),
    sa.Column('fire_type', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('protection_zone', sa.String(), nullable=True),
    sa.Column('prescribed', sa.Boolean(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('attack_date', sa.Date(), nullable=True),
    sa.Column('out_date', sa.Date(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('more_info', sa.String(), nullable=True),
    sa.Column('cfs_note1', sa.String(), nullable=True),
    sa.Column('cfs_note2', sa.String(), nullable=True),
    sa.Column('ignition_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("fire_cause IN ('N', 'H', 'U')", name='ck_nfdb_wildfire_fire_cause'),
    sa.CheckConstraint('size_ha IS NULL OR size_ha >= 0', name='ck_nfdb_wildfire_size_ha'),
    sa.ForeignKeyConstraint(['id'], ['wildfire.id'], ),
    sa.ForeignKeyConstraint(['ignition_id'], ['ignition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nfdb_wildfire_fire_cause', 'nfdb_wildfire', ['fire_cause'], unique=False)
    op.create_index('ix_nfdb_wildfire_ignition_id', 'nfdb_wildfire', ['ignition_id'], unique=False)
    op.create_index('ix_nfdb_wildfire_nfdb_fire_id', 'nfdb_wildfire', ['nfdb_fire_id'], unique=False)
    op.create_index('ix_nfdb_wildfire_src_agency', 'nfdb_wildfire', ['src_agency'], unique=False)
    op.create_index('ix_nfdb_wildfire_year', 'nfdb_wildfire', ['year'], unique=False)
    op.create_geospatial_table('nbac_wildfire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('nfireid', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('part_count', sa.Integer(), nullable=False),
    sa.Column('crosses_admin', sa.Boolean(), nullable=False),
    sa.Column('admin_name', sa.String(), nullable=True),
    sa.Column('admin_div', sa.String(), nullable=True),
    sa.Column('fire_cause', sa.String(), nullable=True),
    sa.Column('ba_source', sa.String(), nullable=True),
    sa.Column('detection_source', sa.String(), nullable=True),
    sa.Column('mapping_method', sa.String(), nullable=True),
    sa.Column('hotspot_start_date', sa.Date(), nullable=True),
    sa.Column('hotspot_end_date', sa.Date(), nullable=True),
    sa.Column('agency_start_date', sa.Date(), nullable=True),
    sa.Column('agency_end_date', sa.Date(), nullable=True),
    sa.Column('capture_date', sa.Date(), nullable=True),
    sa.Column('date_source', sa.String(), nullable=False),
    sa.Column('date_time_precision', sa.String(), nullable=False),
    sa.Column('area_ha_polygon', sa.Float(), nullable=True),
    sa.Column('area_ha_adjusted', sa.Float(), nullable=True),
    sa.Column('area_adjusted', sa.Boolean(), nullable=False),
    sa.Column('prescribed', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('nfdb_wildfire_id', sa.Integer(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('perimeter_lambert', Geometry(geometry_type='MULTIPOLYGON', srid=3978, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.CheckConstraint("date_source IN ('agency', 'hotspot', 'year')", name='ck_nbac_wildfire_date_source'),
    sa.CheckConstraint("date_time_precision IN ('year', 'day')", name='ck_nbac_wildfire_date_time_precision'),
    sa.CheckConstraint("fire_cause IS NULL OR fire_cause IN ('Natural', 'Human', 'Undetermined')", name='ck_nbac_wildfire_fire_cause'),
    sa.CheckConstraint('(nfdb_wildfire_id IS NULL) = (match_method IS NULL)', name='ck_nbac_wildfire_match_method_with_link'),
    sa.CheckConstraint('part_count >= 1', name='ck_nbac_wildfire_part_count'),
    sa.ForeignKeyConstraint(['id'], ['wildfire.id'], ),
    sa.ForeignKeyConstraint(['nfdb_wildfire_id'], ['nfdb_wildfire.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gid', name='uq_nbac_wildfire_gid'),
    sa.UniqueConstraint('year', 'nfireid', name='uq_nbac_wildfire_year_nfireid')
    )
    op.create_geospatial_index('idx_nbac_wildfire_perimeter_lambert', 'nbac_wildfire', ['perimeter_lambert'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_nbac_wildfire_fire_cause', 'nbac_wildfire', ['fire_cause'], unique=False)
    op.create_index('ix_nbac_wildfire_nfdb_wildfire_id', 'nbac_wildfire', ['nfdb_wildfire_id'], unique=False)
    op.create_index('ix_nbac_wildfire_year', 'nbac_wildfire', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision.

    The reverse of the creation order, and it has to be: ``nbac_wildfire`` references
    ``nfdb_wildfire``, which references ``ignition`` through ``nfdb_ignition``. The
    composite goes first, then the reports, then the points.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nbac_wildfire_year', table_name='nbac_wildfire')
    op.drop_index('ix_nbac_wildfire_nfdb_wildfire_id', table_name='nbac_wildfire')
    op.drop_index('ix_nbac_wildfire_fire_cause', table_name='nbac_wildfire')
    op.drop_geospatial_index('idx_nbac_wildfire_perimeter_lambert', table_name='nbac_wildfire', postgresql_using='gist', column_name='perimeter_lambert')
    op.drop_geospatial_table('nbac_wildfire')
    op.drop_index('ix_nfdb_wildfire_year', table_name='nfdb_wildfire')
    op.drop_index('ix_nfdb_wildfire_src_agency', table_name='nfdb_wildfire')
    op.drop_index('ix_nfdb_wildfire_nfdb_fire_id', table_name='nfdb_wildfire')
    op.drop_index('ix_nfdb_wildfire_ignition_id', table_name='nfdb_wildfire')
    op.drop_index('ix_nfdb_wildfire_fire_cause', table_name='nfdb_wildfire')
    op.drop_table('nfdb_wildfire')
    op.drop_index('ix_nfdb_ignition_year', table_name='nfdb_ignition')
    op.drop_index('ix_nfdb_ignition_nfdb_fire_id', table_name='nfdb_ignition')
    op.drop_geospatial_index('idx_nfdb_ignition_geometry_lambert', table_name='nfdb_ignition', postgresql_using='gist', column_name='geometry_lambert')
    op.drop_geospatial_table('nfdb_ignition')
    # ### end Alembic commands ###
