"""add admin boundary and ocha admin boundary

Revision ID: 0191822a7bae
Revises: 8073d0a07f27
Create Date: 2026-07-20 13:33:08.160304+00:00
"""
from __future__ import annotations

from typing import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op
from geoalchemy2 import Geometry
# revision identifiers, used by Alembic.
revision: str = '0191822a7bae'
down_revision: str | None = '8073d0a07f27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('admin_boundary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data_provider_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_provider_id'], ['data_provider.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_boundary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_provider_id', 'source_id', name='uq_admin_boundary_provider_source')
    )
    op.create_geospatial_index('idx_admin_boundary_geometry', 'admin_boundary', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_admin_boundary_level', 'admin_boundary', ['level'], unique=False)
    op.create_index('ix_admin_boundary_parent_id', 'admin_boundary', ['parent_id'], unique=False)
    op.create_table('ocha_admin_boundary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('name_alt', sa.String(), nullable=True),
    sa.Column('iso_code', sa.Integer(), nullable=False),
    sa.Column('iso_2', sa.String(), nullable=False),
    sa.Column('iso_3', sa.String(), nullable=False),
    sa.Column('iso_3_group', sa.String(), nullable=False),
    sa.Column('region1_code', sa.Integer(), nullable=False),
    sa.Column('region1_name', sa.String(), nullable=False),
    sa.Column('region2_code', sa.Integer(), nullable=False),
    sa.Column('region2_name', sa.String(), nullable=False),
    sa.Column('region3_code', sa.Integer(), nullable=False),
    sa.Column('region3_name', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('valid_date', sa.Date(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('land_source', sa.String(), nullable=False),
    sa.Column('view', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['admin_boundary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocha_admin_boundary')
    op.drop_index('ix_admin_boundary_parent_id', table_name='admin_boundary')
    op.drop_index('ix_admin_boundary_level', table_name='admin_boundary')
    op.drop_geospatial_index('idx_admin_boundary_geometry', table_name='admin_boundary', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('admin_boundary')
    # ### end Alembic commands ###
