"""initial schema: data_provider and wildfire

Revision ID: 563e89574195
Revises: 
Create Date: 2026-07-19 21:08:59.022311+00:00
"""
from __future__ import annotations

from typing import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '563e89574195'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # PostGIS must exist before any geometry column is created. Added by hand:
    # autogenerate does not track extensions.
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'product', name='uq_data_provider_name_product')
    )
    op.create_geospatial_table('wildfire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data_provider_id', sa.Integer(), nullable=False),
    sa.Column('start_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('perimeter', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_provider_id'], ['data_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_wildfire_perimeter', 'wildfire', ['perimeter'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_wildfire_perimeter', table_name='wildfire', postgresql_using='gist', column_name='perimeter')
    op.drop_geospatial_table('wildfire')
    op.drop_table('data_provider')
    # ### end Alembic commands ###

    # The postgis extension is deliberately NOT dropped: other schemas in the
    # same database may depend on it.
