"""add gfa wildfire

Revision ID: 6a1410b5fe22
Revises: 065ea7408253
Create Date: 2026-07-22 16:27:43.359843+00:00
"""
from __future__ import annotations

from typing import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op
from geoalchemy2 import Geometry
# revision identifiers, used by Alembic.
revision: str = '6a1410b5fe22'
down_revision: str | None = '065ea7408253'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('gfa_wildfire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gfa_id', sa.Integer(), nullable=False),
    sa.Column('ignition_point', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('size_km2', sa.Float(), nullable=True),
    sa.Column('perimeter_km', sa.Float(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('fire_line_km', sa.Float(), nullable=True),
    sa.Column('spread_km2_day', sa.Float(), nullable=True),
    sa.Column('speed_km_day', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('direction_fraction', sa.Float(), nullable=True),
    sa.Column('modis_tile', sa.String(), nullable=True),
    sa.Column('landcover', sa.String(), nullable=True),
    sa.Column('landcover_fraction', sa.Float(), nullable=True),
    sa.Column('gfed_region', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['wildfire.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gfa_id')
    )
    op.create_geospatial_index('idx_gfa_wildfire_ignition_point', 'gfa_wildfire', ['ignition_point'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_gfa_wildfire_ignition_point', table_name='gfa_wildfire', postgresql_using='gist', column_name='ignition_point')
    op.drop_geospatial_table('gfa_wildfire')
    # ### end Alembic commands ###
