"""add iso_name to ocha admin boundary

Revision ID: aa607cd83555
Revises: 0191822a7bae
Create Date: 2026-07-20 17:45:48.817382+00:00
"""
from __future__ import annotations

from typing import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa607cd83555'
down_revision: str | None = '0191822a7bae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocha_admin_boundary', sa.Column('iso_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocha_admin_boundary', 'iso_name')
    # ### end Alembic commands ###
