"""make ocha iso_2 nullable

Revision ID: 42c012409131
Revises: aa607cd83555
Create Date: 2026-07-20 18:31:14.417567+00:00
"""
from __future__ import annotations

from typing import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42c012409131'
down_revision: str | None = 'aa607cd83555'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ocha_admin_boundary', 'iso_2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ocha_admin_boundary', 'iso_2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
